import type { Design } from "../types";
export const mockDesigns: Design[] = [
  {
    id: "d1",
    title: "Vaso Geometrico Voronoi",
    subtitle: "Design parametrico a bassa infill",
    publishedAt: "2026-05-10T12:00:00Z",
    designerId: "u2",
    technology: "FDM",
    stlFileUrl: "/mock-files/vaso-voronoi.stl",
    description:
      "Vaso decorativo stampabile senza supporti, pattern voronoi generato parametricamente.",
    photoUrls: [
      "https://picsum.photos/seed/vaso1/600/400",
      "https://picsum.photos/seed/vaso2/600/400",
    ],
    rating: 4.5,
    price: 6.99,
    tags: ["casa", "decorativo", "voronoi"],
  },
  {
    id: "d2",
    title: "Miniatura Drago Articolato",
    publishedAt: "2026-06-02T09:00:00Z",
    designerId: "u2",
    technology: "Resin",
    stlFileUrl: "/mock-files/drago-articolato.stl",
    description:
      "Drago snodabile stampabile in un solo pezzo, articolazioni print-in-place.",
    photoUrls: [
      "https://picsum.photos/seed/drago1/600/400",
      "https://picsum.photos/seed/drago2/600/400",
      "https://picsum.photos/seed/drago3/600/400",
    ],
    videoUrls: ["https://example.com/mock-video/drago.mp4"],
    rating: 4.8,
    price: 12.5,
    tags: ["miniatura", "fantasy", "articolato"],
  },
  {
    id: "d3",
    title: "Portachiavi Logo Custom",
    publishedAt: "2026-06-15T16:30:00Z",
    designerId: "u3",
    technology: "FDM",
    stlFileUrl: "/mock-files/portachiavi.stl",
    photoUrls: ["https://picsum.photos/seed/porta1/600/400"],
    rating: 3.9,
    price: 2.5,
    tags: ["gadget", "personalizzabile"],
  },
  {
    id: "d4",
    title: "Supporto Cuffie da Scrivania",
    subtitle: "Design minimale con cable management",
    publishedAt: "2026-07-01T11:00:00Z",
    designerId: "u3",
    technology: "FDM",
    stlFileUrl: "/mock-files/supporto-cuffie.stl",
    description:
      "Supporto stabile con foro passacavi integrato, nessun supporto necessario in stampa.",
    photoUrls: [
      "https://picsum.photos/seed/cuffie1/600/400",
      "https://picsum.photos/seed/cuffie2/600/400",
    ],
    rating: 4.2,
    price: 4.0,
    tags: ["scrivania", "organizzazione", "minimal"],
  },
  {
    id: "d5",
    title: "Ingranaggio Planetario Dimostrativo",
    publishedAt: "2026-07-18T08:45:00Z",
    designerId: "u2",
    technology: "FDM",
    stlFileUrl: "/mock-files/ingranaggio-planetario.stl",
    description:
      "Modello didattico di trasmissione planetaria, stampabile assemblato print-in-place.",
    photoUrls: ["https://picsum.photos/seed/gear1/600/400"],
    videoUrls: ["https://example.com/mock-video/ingranaggio.mp4"],
    rating: 5.0,
    price: 9.99,
    tags: ["meccanica", "didattico", "ingranaggi"],
  },
];
