import type { User } from "../types";
export const mockUser: User[] = [
  {
    id: "u0",
    firstName: "Mario",
    lastName: "Fiorucci",
    email: "MarioFiorucci@gmail.com",
    passwordHash: "fasfea",
    role: "CUSTOMER",
    profilePhotoUrl: "http://placecats.com/300/200",
    backgroundPhotoUrl: "https://placecats.com/200/300",
    location: "Rome, IT",
    createdAt: "03/05/2000",
  },
  {
    id: "u1",
    firstName: "Marco",
    lastName: "Bianchi",
    email: "marco.bianchi@example.com",
    passwordHash: "hashed_placeholder_1",
    role: "CUSTOMER",
    profilePhotoUrl: "https://i.pravatar.cc/150?img=12",
    location: "Milano, IT",
    tags: ["stampa3d", "hobbista"],
    createdAt: "2026-03-14T10:00:00Z",
  },
  {
    id: "u2",
    firstName: "Giulia",
    lastName: "Romano",
    email: "giulia.romano@example.com",
    passwordHash: "hashed_placeholder_2",
    role: "DESIGNER",
    profilePhotoUrl: "https://i.pravatar.cc/150?img=45",
    backgroundPhotoUrl: "https://picsum.photos/seed/giulia/800/300",
    location: "Torino, IT",
    tags: ["designer", "miniature"],
    iban: "IT60X0542811101000000123456",
    designerLevel: "PROFESSIONAL",
    createdAt: "2026-02-01T09:30:00Z",
  },
  {
    id: "u3",
    firstName: "Luca",
    lastName: "Ferri",
    email: "luca.ferri@example.com",
    passwordHash: "hashed_placeholder_3",
    role: "DESIGNER",
    profilePhotoUrl: "https://i.pravatar.cc/150?img=33",
    location: "Bologna, IT",
    tags: ["amatoriale", "gadget"],
    iban: "IT28W8000000292100645211151",
    designerLevel: "AMATEUR",
    createdAt: "2026-04-20T14:15:00Z",
  },
];
