spring.application.name=Layerly-backend
spring.config.import=file:env.properties

# SERVER CONFIG
server.port=${SERVER_PORT}
# DB CONFIG
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver=org.postgresql.Driver
# HIBERNATE
spring.jpa.hibernate.ddl-auto=validate
# JWT
jwt.secret=${TOKEN_PW}

# MIGRATION
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration